#!/usr/bin/env bash
# bootstrap-detect.sh — probe local hardware and print suggested host_vars YAML.
# Paste the output into ansible/inventory/host_vars/$(hostname).yml.
#
# Usage: ./bootstrap-detect.sh

set -euo pipefail

HOSTNAME=$(hostname -s)
HAS_GPU=false
HAS_STORAGE=false
NODE_ROLE=edge
STORAGE_THRESHOLD_BYTES=$((2 * 1024 * 1024 * 1024 * 1024))  # 2 TB

# --- GPU detection ---
if command -v lspci &>/dev/null; then
    if lspci 2>/dev/null | grep -qiE 'nvidia|amd.*radeon|advanced micro devices.*vga'; then
        HAS_GPU=true
    fi
fi

# --- Storage detection ---
# Sum all block device sizes reported by lsblk (bytes), exclude loop/rom devices.
if command -v lsblk &>/dev/null; then
    total_bytes=0
    while IFS= read -r size; do
        [[ -z "$size" || "$size" == "0" ]] && continue
        total_bytes=$(( total_bytes + size ))
    done < <(lsblk -b -d -n -o SIZE,TYPE 2>/dev/null | awk '$2 == "disk" {print $1}')

    if (( total_bytes >= STORAGE_THRESHOLD_BYTES )); then
        HAS_STORAGE=true
    fi
fi

# --- Role heuristic ---
if [[ "$HAS_GPU" == "true" ]]; then
    NODE_ROLE=edge   # GPU nodes are edge nodes; override to 'gpu' sub-role in job specs
elif [[ "$HAS_STORAGE" == "true" ]]; then
    NODE_ROLE=storage
fi

# --- Output ---
cat <<EOF
# Suggested host_vars for: ${HOSTNAME}
# Generated by bootstrap-detect.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Review and adjust before running ansible-playbook bootstrap.yml.
# Save to: ansible/inventory/host_vars/${HOSTNAME}.yml

node_role: ${NODE_ROLE}
has_storage: ${HAS_STORAGE}
has_gpu: ${HAS_GPU}

# consul_datacenter: home   # or 'cloud' for VPS/remote nodes
# consul_server: false      # set true on 3 light/vps nodes
# nomad_server: false       # set true on 3 light/vps nodes

# netbird_setup_key is sensitive — set in Ansible vault, not here.
EOF

# Print detected details for operator review
echo ""
echo "# Detection details:"

if command -v lspci &>/dev/null; then
    gpu_lines=$(lspci 2>/dev/null | grep -iE 'nvidia|amd.*radeon|advanced micro devices.*vga' || true)
    if [[ -n "$gpu_lines" ]]; then
        echo "# GPUs found:"
        while IFS= read -r line; do
            echo "#   $line"
        done <<< "$gpu_lines"
    else
        echo "# No GPU detected"
    fi
fi

if command -v lsblk &>/dev/null; then
    echo "# Block devices:"
    lsblk -b -d -n -o NAME,SIZE,MODEL 2>/dev/null | awk '$2 > 0 {printf "#   %-10s %8.1f GB   %s\n", $1, $2/1024/1024/1024, $3}' || true
fi
