# SOPS configuration for encrypted secrets
# Single secrets file for both dev and prod

creation_rules:
  - path_regex: provisioning\.secrets\.yaml$
    age: >-
      age1m2w4k4rgnzdynx0s9xqvx7k66dfa4jv5q20hgxp6dcjjwz09mdlqqzgves,
      age1zczw97ae7g22fsr4ys4776ty88pkydr48y6lqzxms8qw6mhge9fq0f03kc

  - path_regex: cluster\.secrets\.yaml$
    age: >-
      age1m2w4k4rgnzdynx0s9xqvx7k66dfa4jv5q20hgxp6dcjjwz09mdlqqzgves,
      age1zczw97ae7g22fsr4ys4776ty88pkydr48y6lqzxms8qw6mhge9fq0f03kc,
